ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS hero_height TEXT NOT NULL DEFAULT 'normal',
  ADD COLUMN IF NOT EXISTS hero_autoplay BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS hero_autoplay_delay INTEGER NOT NULL DEFAULT 5500,
  ADD COLUMN IF NOT EXISTS hero_show_cta BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS hero_image_fit TEXT NOT NULL DEFAULT 'cover';